$(document).ready(function(){
	$("#btnLogin").click(function(e){
		e.preventDefault();
		$.post("ver/",$("#frmLogin").serialize(),function(data){
			if(data=="OK"){
				window.location.assing('http://localhost/Minardi/P2/app/produtos')
			}
			else{
				alert(data);
			}
		});
	});
});